/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.partner.model;

import com.jfeat.partner.model.base.AgentPurchaseJournalBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

import java.math.BigDecimal;
import java.util.List;

@TableBind(tableName = "t_agent_purchase_journal")
public class AgentPurchaseJournal extends AgentPurchaseJournalBase<AgentPurchaseJournal> {

    /**
     * Only use for query.
     */
    public static AgentPurchaseJournal dao = new AgentPurchaseJournal();

    public List<AgentPurchaseJournal> findBySellerId(int sellerId) {
        String sql = "select * from t_agent_purchase_journal where seller_id=? order by create_date asc,id asc";
        return find(sql, sellerId);
    }

    public Page<AgentPurchaseJournal> paginateBySellerId(Integer pageNumber, Integer pageSize, Integer sellerId) {
        String sql = "select *";
        String sqlExceptSelect = " from t_agent_purchase_journal where seller_id=? order by id desc";
        return paginate(pageNumber, pageSize, sql, sqlExceptSelect, sellerId);
    }

//    public List<AgentPurchaseJournal> findBySellerIdPcdIdBetweenCreateDate(int sellerId, int pcdId, String startTime, String endTime) {
//        String sql = "select * from t_agent_purchase_journal" +
//                " where seller_id=? and pcd_id=? and create_date between ? and ?";
//        return find(sql, sellerId, pcdId, startTime, endTime);
//    }

    public List<AgentPurchaseJournal> findBySellerIdPcdIdBetweenCreateDate(int sellerId, int pcdId, String startTime, String endTime) {
        String sql = "select product_id,product_name, " +
                " format(agent_proportion * percentage / 100, 2) as agent_proportion_percentage, " +
                " sum(final_price) as sum_final_price, sum(settled_amount) as sum_settled_amount " +
                " from t_agent_purchase_journal" +
                " where seller_id=? and pcd_id=? and create_date between ? and ?" +
                " group by product_id,product_name,percentage,agent_proportion";
        return find(sql, sellerId, pcdId, startTime, endTime);
    }

    /**
     * 计算某个seller的某个地区的某段时间的订单额总和
     *
     * @param sellerId
     * @param pcdId
     * @param startTime
     * @param endTime
     * @return
     */
    public BigDecimal getTotalAmount(int sellerId, int pcdId, String startTime, String endTime) {
        String sql = "select ifnull(sum(final_price),0) as sum from t_agent_purchase_journal" +
                " where seller_id=? and pcd_id=? and (create_date between ? and ?)";
        return Db.queryBigDecimal(sql, sellerId, pcdId, startTime, endTime);
    }
}
