/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.partner.model;

import com.jfeat.partner.model.base.AgentPcdQualifyBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfeat.partner.model.Agent;
import com.jfeat.partner.model.PcdQualify;

import java.util.Date;
import java.util.List;

@TableBind(tableName = "t_agent_pcd_qualify")
public class AgentPcdQualify extends AgentPcdQualifyBase<AgentPcdQualify> {

    /**
     * Only use for query.
     */
    public static AgentPcdQualify dao = new AgentPcdQualify();

    public List<AgentPcdQualify> findByAgentId(Integer agentId) {
        return findByField(Fields.AGENT_ID.toString(), agentId);
    }

    public Agent getAgent() {
        return Agent.dao.findById(getAgentId());
    }

    public List<AgentPcdQualify> findByPcdQualifyId(Integer pcdQualifyId) {
        return findByField(Fields.PCD_QUALIFY_ID.toString(), pcdQualifyId);
    }

    public PcdQualify getPcdQualify() {
        return PcdQualify.dao.findById(getPcdQualifyId());
    }

    public AgentPcdQualify findByAgentIdAndPcdQualifyId(Integer agentId, Integer pcdQualifyId) {
        return findFirst("select * from t_agent_pcd_qualify where agent_id = ? and pcd_qualify_id = ?", agentId, pcdQualifyId);
    }

    public boolean save() {
        setCreateTime(new Date());
        return super.save();
    }

    /**
     * 找出代理了某个地区的代理商
     * @param pcdId
     * @return
     */
    public List<AgentPcdQualify> findAllByPcdId(int pcdId) {
        String sql = "select b.* from t_agent as a" +
                " join t_agent_pcd_qualify as b on a.id=b.agent_id" +
                " join t_pcd_qualify as c on b.pcd_qualify_id=c.id" +
                " where c.pcd_id=?";
        return find(sql, pcdId);
    }
}
