/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.partner.model;

import com.jfeat.partner.model.base.CooperativeStatisticBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

@TableBind(tableName = "t_cooperative_statistic")
public class CooperativeStatistic extends CooperativeStatisticBase<CooperativeStatistic> {

    /**
     * Only use for query.
     */
    public static CooperativeStatistic dao = new CooperativeStatistic();

    public List<CooperativeStatistic> find(String startTime, String endTime) {
        return find("select * from t_cooperative_statistic" +
                " where real_date between ? and ?" +
                " order by real_date asc", startTime, endTime);
    }

    public Page<CooperativeStatistic> paginate(Integer pageNumber, Integer pageSize, String startTime, String endTime) {
        return paginate(pageNumber, pageSize, "select *", " from t_cooperative_statistic" +
                " where real_date between ? and ?" +
                " order by real_date asc", startTime, endTime);
    }
}
