/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.partner.model;

import com.jfeat.partner.model.base.CopartnerSettlementBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfeat.partner.model.Copartner;

import java.util.List;

@TableBind(tableName = "t_copartner_settlement")
public class CopartnerSettlement extends CopartnerSettlementBase<CopartnerSettlement> {

    /**
     * Only use for query.
     */
    public static CopartnerSettlement dao = new CopartnerSettlement();

    public static final Integer TRANSFERRED = 1;
    public static final Integer UN_TRANSFERRED = 0;

    public CopartnerSettlement findByCond(Integer copartnerId, String month) {
        String sql = "select * from t_copartner_settlement where copartner_id = ? and statistic_month = ?";
        return findFirst(sql, copartnerId, month);
    }

    public Copartner getCopartner() {
        return Copartner.dao.findById(getCopartnerId());
    }

}
