/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.partner.model;

import com.jfeat.partner.model.base.PcdQualifyBase;
import com.jfeat.pcd.model.Pcd;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import java.util.ArrayList;
import java.util.List;

@TableBind(tableName = "t_pcd_qualify")
public class PcdQualify extends PcdQualifyBase<PcdQualify> {

    /**
     * Only use for query.
     */
    public static PcdQualify dao = new PcdQualify();

    public Pcd getPcd() {
        return Pcd.dao.findById(getPcdId());
    }

    public PcdQualify findByPcdId(int pcdId) {
        return findFirst("select * from t_pcd_qualify pq join t_pcd p on pq.pcd_id=p.id where p.id=?", pcdId);
    }

    public List<Record> queryPcd(String type, Integer parentId) {
        StringBuilder query = new StringBuilder("select p.name,p.type,p.parent_id,pq.*" +
                "from t_pcd p, t_pcd_qualify pq " +
                "where pq.pcd_id = p.id");
        List<Object> params = new ArrayList<>();
        if (StrKit.notBlank(type)){
            query.append(" and p.type=?");
            params.add(type);
        }
        if (parentId != null){
            query.append(" and p.parent_id=?");
            params.add(parentId);
        }
        return Db.find(query.toString(),params.toArray());
    }

}
