/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.partner.model;

import com.jfeat.kit.SqlQuery;
import com.jfeat.partner.model.base.PhysicalSettlementDefinitionBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

@TableBind(tableName = "t_physical_settlement_definition")
public class PhysicalSettlementDefinition extends PhysicalSettlementDefinitionBase<PhysicalSettlementDefinition> {

    /**
     * Only use for query.
     */
    public static PhysicalSettlementDefinition dao = new PhysicalSettlementDefinition();

    public PhysicalSettlementDefinition getDefault() {
        return findFirst(new SqlQuery().from(getTableName()).sql());
    }

    public boolean save() {
        throw new RuntimeException("Not allowed operation.");
    }

    public boolean delete() {
        throw new RuntimeException("Not allowed operation.");
    }

}
