/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.marketing.wholesale.model;

import com.jfeat.marketing.wholesale.model.base.WholesalePricingBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_wholesale_pricing")
public class WholesalePricing extends WholesalePricingBase<WholesalePricing> {

    /**
     * Only use for query.
     */
    public static WholesalePricing dao = new WholesalePricing();

    public List<WholesalePricing> findByWholesaleId(Integer wholesaleId) {
        return findByField(Fields.WHOLESALE_ID.toString(), wholesaleId);
    }

    public Wholesale getWholesale() {
        return Wholesale.dao.findById(getWholesaleId());
    }

}
