/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.marketing.wholesale.model;

import com.jfeat.marketing.wholesale.model.base.WholesaleCategoryBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_wholesale_category")
public class WholesaleCategory extends WholesaleCategoryBase<WholesaleCategory> {

    /**
     * Only use for query.
     */
    public static WholesaleCategory dao = new WholesaleCategory();

    @Override
    public List<WholesaleCategory> findAll() {
        return find("select * from t_wholesale_category order by sort_order asc,id desc");
    }

}
