/*
 *   Copyright (C) 2014-2019 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.order.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class OrderExpressBase<M extends OrderExpressBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        ORDER_ID("order_id"),
        MID("mid"),
        CREATE_DATE("create_date"),
        EXPRESS_COMPANY("express_company"),
        EXPRESS_CODE("express_code"),
        EXPRESS_NUMBER("express_number"),
        ORDER_ITEMS("order_items");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setOrderId(Integer var) {
        set(Fields.ORDER_ID.toString(), var);
    }

    public Integer getOrderId() {
        return (Integer) get(Fields.ORDER_ID.toString());
    }

    public void setMid(Integer var) {
        set(Fields.MID.toString(), var);
    }

    public Integer getMid() {
        return (Integer) get(Fields.MID.toString());
    }

    public void setCreateDate(Date var) {
        set(Fields.CREATE_DATE.toString(), var);
    }

    public Date getCreateDate() {
        return (Date) get(Fields.CREATE_DATE.toString());
    }

    public void setExpressCompany(String var) {
        set(Fields.EXPRESS_COMPANY.toString(), var);
    }

    public String getExpressCompany() {
        return (String) get(Fields.EXPRESS_COMPANY.toString());
    }

    public void setExpressCode(String var) {
        set(Fields.EXPRESS_CODE.toString(), var);
    }

    public String getExpressCode() {
        return (String) get(Fields.EXPRESS_CODE.toString());
    }

    public void setExpressNumber(String var) {
        set(Fields.EXPRESS_NUMBER.toString(), var);
    }

    public String getExpressNumber() {
        return (String) get(Fields.EXPRESS_NUMBER.toString());
    }

    public void setOrderItems(String var) {
        set(Fields.ORDER_ITEMS.toString(), var);
    }

    public String getOrderItems() {
        return (String) get(Fields.ORDER_ITEMS.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
