/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.marketing.wholesale.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class WholesaleBase<M extends WholesaleBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        MARKETING_NAME("marketing_name"),
        MARKETING_SHORT_NAME("marketing_short_name"),
        CATEGORY_ID("category_id"),
        PRODUCT_ID("product_id"),
        SALE("sale"),
        COVER("cover"),
        STATUS("status"),
        DESCRIPTION("description"),
        SETTLEMENT_PROPORTION("settlement_proportion"),
        AGENT_PROPORTION("agent_proportion"),
        SORT_ORDER("sort_order"),
        UNIT("unit"),
        SUGGESTED_RETAIL_UNIT("suggested_retail_unit"),
        SUGGESTED_WHOLESALE_UNIT("suggested_wholesale_unit");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setMarketingName(String var) {
        set(Fields.MARKETING_NAME.toString(), var);
    }

    public String getMarketingName() {
        return (String) get(Fields.MARKETING_NAME.toString());
    }

    public void setMarketingShortName(String var) {
        set(Fields.MARKETING_SHORT_NAME.toString(), var);
    }

    public String getMarketingShortName() {
        return (String) get(Fields.MARKETING_SHORT_NAME.toString());
    }

    public void setCategoryId(Integer var) {
        set(Fields.CATEGORY_ID.toString(), var);
    }

    public Integer getCategoryId() {
        return (Integer) get(Fields.CATEGORY_ID.toString());
    }

    public void setProductId(Integer var) {
        set(Fields.PRODUCT_ID.toString(), var);
    }

    public Integer getProductId() {
        return (Integer) get(Fields.PRODUCT_ID.toString());
    }

    public void setSale(Integer var) {
        set(Fields.SALE.toString(), var);
    }

    public Integer getSale() {
        return (Integer) get(Fields.SALE.toString());
    }

    public void setCover(String var) {
        set(Fields.COVER.toString(), var);
    }

    public String getCover() {
        return (String) get(Fields.COVER.toString());
    }

    public void setStatus(String var) {
        set(Fields.STATUS.toString(), var);
    }

    public String getStatus() {
        return (String) get(Fields.STATUS.toString());
    }

    public void setDescription(String var) {
        set(Fields.DESCRIPTION.toString(), var);
    }

    public String getDescription() {
        return (String) get(Fields.DESCRIPTION.toString());
    }

    public void setSettlementProportion(Integer var) {
        set(Fields.SETTLEMENT_PROPORTION.toString(), var);
    }

    public Integer getSettlementProportion() {
        return (Integer) get(Fields.SETTLEMENT_PROPORTION.toString());
    }

    public void setAgentProportion(BigDecimal var) {
        set(Fields.AGENT_PROPORTION.toString(), var);
    }

    public BigDecimal getAgentProportion() {
        return (BigDecimal) get(Fields.AGENT_PROPORTION.toString());
    }

    public void setSortOrder(Integer var) {
        set(Fields.SORT_ORDER.toString(), var);
    }

    public Integer getSortOrder() {
        return (Integer) get(Fields.SORT_ORDER.toString());
    }

    public void setUnit(String var) {
        set(Fields.UNIT.toString(), var);
    }

    public String getUnit() {
        return (String) get(Fields.UNIT.toString());
    }

    public void setSuggestedRetailUnit(String var) {
        set(Fields.SUGGESTED_RETAIL_UNIT.toString(), var);
    }

    public String getSuggestedRetailUnit() {
        return (String) get(Fields.SUGGESTED_RETAIL_UNIT.toString());
    }

    public void setSuggestedWholesaleUnit(String var) {
        set(Fields.SUGGESTED_WHOLESALE_UNIT.toString(), var);
    }

    public String getSuggestedWholesaleUnit() {
        return (String) get(Fields.SUGGESTED_WHOLESALE_UNIT.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
