/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.marketing.wholesale.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class WholesalePricingBase<M extends WholesalePricingBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        WHOLESALE_ID("wholesale_id"),
        REGION("region"),
        PRICE("price"),
        SUGGESTED_RETAIL_PRICE("suggested_retail_price"),
        SUGGESTED_WHOLESALE_PRICE("suggested_wholesale_price"),
        IS_DEFAULT("is_default"),
        ENABLED("enabled");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setWholesaleId(Integer var) {
        set(Fields.WHOLESALE_ID.toString(), var);
    }

    public Integer getWholesaleId() {
        return (Integer) get(Fields.WHOLESALE_ID.toString());
    }

    public void setRegion(String var) {
        set(Fields.REGION.toString(), var);
    }

    public String getRegion() {
        return (String) get(Fields.REGION.toString());
    }

    public void setPrice(BigDecimal var) {
        set(Fields.PRICE.toString(), var);
    }

    public BigDecimal getPrice() {
        return (BigDecimal) get(Fields.PRICE.toString());
    }

    public void setSuggestedRetailPrice(BigDecimal var) {
        set(Fields.SUGGESTED_RETAIL_PRICE.toString(), var);
    }

    public BigDecimal getSuggestedRetailPrice() {
        return (BigDecimal) get(Fields.SUGGESTED_RETAIL_PRICE.toString());
    }

    public void setSuggestedWholesalePrice(BigDecimal var) {
        set(Fields.SUGGESTED_WHOLESALE_PRICE.toString(), var);
    }

    public BigDecimal getSuggestedWholesalePrice() {
        return (BigDecimal) get(Fields.SUGGESTED_WHOLESALE_PRICE.toString());
    }

    public void setIsDefault(Integer var) {
        set(Fields.IS_DEFAULT.toString(), var);
    }

    public Integer getIsDefault() {
        return (Integer) get(Fields.IS_DEFAULT.toString());
    }

    public void setEnabled(Integer var) {
        set(Fields.ENABLED.toString(), var);
    }

    public Integer getEnabled() {
        return (Integer) get(Fields.ENABLED.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
