/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.member.model;

import com.jfeat.member.model.base.CouponStrategyTakenRecordBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfeat.member.model.CouponStrategy;
import com.jfeat.identity.model.User;
import com.jfinal.plugin.activerecord.Db;

import java.util.Date;


@TableBind(tableName = "t_coupon_strategy_taken_record")
public class CouponStrategyTakenRecord extends CouponStrategyTakenRecordBase<CouponStrategyTakenRecord> {

    /**
     * Only use for query.
     */
    public static CouponStrategyTakenRecord dao = new CouponStrategyTakenRecord();

    public boolean isTaken(Integer strategyId, Integer userId, Integer version) {
        return Db.queryNumber("select count(1) from t_coupon_strategy_taken_record where strategy_id = ? and user_id = ? and version = ?", strategyId, userId, version).intValue() > 0;
    }

    public CouponStrategy getCouponStrategy() {
        return CouponStrategy.dao.findById(getStrategyId());
    }

    public User getUser() {
        return User.dao.findById(getUserId());
    }

    @Override
    public boolean save() {
        setCreatedDate(new Date());
        return super.save();
    }
}
