/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.member.model;

import com.jfeat.member.model.base.CouponTakenRecordBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;

import java.util.Date;
import java.util.List;

@TableBind(tableName = "t_coupon_taken_record")
public class CouponTakenRecord extends CouponTakenRecordBase<CouponTakenRecord> {

    /**
     * Only use for query.
     */
    public static CouponTakenRecord dao = new CouponTakenRecord();

    public CouponTakenRecord findByUserIdAndShareId(Integer userId, Integer shareId) {
        return findFirst("select * from t_coupon_taken_record where user_id=? and share_id=?", userId, shareId);
    }

    public List<CouponTakenRecord> findByShareId(int shareId) {
        return find("select a.*, b.name from t_coupon_taken_record a join t_user b on a.user_id=b.id where share_id=?", shareId);
    }
}
