/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.member.model;

import com.jfeat.kit.SqlQuery;
import com.jfeat.member.model.base.MemberExtBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

@TableBind(tableName = "t_member_ext")
public class MemberExt extends MemberExtBase<MemberExt> {

    /**
     * Only use for query.
     */
    public static MemberExt dao = new MemberExt();

    public MemberExt findByUserId(int userId) {
        SqlQuery query = new SqlQuery();
        query.from(getTableName());
        query.where(Fields.USER_ID.eq("?"));
        return findFirst(query.sql(), userId);
    }

    public MemberLevel getLevel() {
        return MemberLevel.dao.findById(getLevelId());
    }

}
