/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.wechat.model;

import com.jfeat.wechat.model.base.WechatFieldBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

@TableBind(tableName = "t_wechat_field")
public class WechatField extends WechatFieldBase<WechatField> {

    /**
     * Only use for query.
     */
    public static WechatField dao = new WechatField();

    public int deleteByTemplateMessageId(Integer templateMessageId) {
        return Db.update("delete from t_wechat_field where template_message_id=?", templateMessageId);
    }

    public WechatField findByPropIdAndTemplateMessageId(Integer propId, Integer templateMessageId) {
        return findFirst("select * from t_wechat_field where prop_id=? and template_message_id=?", propId, templateMessageId);
    }

    public List<WechatField> findByTemplateMessageId(Integer templateMessageId) {
        return find("select * from t_wechat_field where template_message_id=?", templateMessageId);
    }

}
