/*
 *   Copyright (C) 2014-2019 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.partner.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class PcdQualifyBase<M extends PcdQualifyBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        PCD_ID("pcd_id"),
        TURNOVER_QUOTA("turnover_quota"),
        CASH_DEPOSIT("cash_deposit"),
        ALLOW_INFERIOR("allow_inferior"),
        PHYSICAL_SETTLEMENT_PERCENTAGE("physical_settlement_percentage");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setPcdId(Integer var) {
        set(Fields.PCD_ID.toString(), var);
    }

    public Integer getPcdId() {
        return (Integer) get(Fields.PCD_ID.toString());
    }

    public void setTurnoverQuota(Integer var) {
        set(Fields.TURNOVER_QUOTA.toString(), var);
    }

    public Integer getTurnoverQuota() {
        return (Integer) get(Fields.TURNOVER_QUOTA.toString());
    }

    public void setCashDeposit(Integer var) {
        set(Fields.CASH_DEPOSIT.toString(), var);
    }

    public Integer getCashDeposit() {
        return (Integer) get(Fields.CASH_DEPOSIT.toString());
    }

    public void setAllowInferior(Short var) {
        set(Fields.ALLOW_INFERIOR.toString(), var);
    }

    public Short getAllowInferior() {
        return (Short) get(Fields.ALLOW_INFERIOR.toString());
    }

    public void setPhysicalSettlementPercentage(Integer var) {
        set(Fields.PHYSICAL_SETTLEMENT_PERCENTAGE.toString(), var);
    }

    public Integer getPhysicalSettlementPercentage() {
        return (Integer) get(Fields.PHYSICAL_SETTLEMENT_PERCENTAGE.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
