/*
 *   Copyright (C) 2014-2019 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.partner.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class PhysicalPurchaseJournalBase<M extends PhysicalPurchaseJournalBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        SELLER_ID("seller_id"),
        AMOUNT("amount"),
        NOTE("note"),
        CREATED_DATE("created_date"),
        ORDER_NUMBER("order_number"),
        ORDER_ID("order_id"),
        ORDER_ITEM_ID("order_item_id"),
        PRODUCT_NAME("product_name"),
        PRODUCT_SETTLEMENT_PROPORTION("product_settlement_proportion"),
        EXPECTED_REWARD("expected_reward"),
        EXPECTED_REWARD_LV1("expected_reward_lv1"),
        EXPECTED_REWARD_LV2("expected_reward_lv2"),
        SETTLEMENT_PROPORTION_LV1("settlement_proportion_lv1"),
        SETTLEMENT_PROPORTION_LV2("settlement_proportion_lv2");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setSellerId(Integer var) {
        set(Fields.SELLER_ID.toString(), var);
    }

    public Integer getSellerId() {
        return (Integer) get(Fields.SELLER_ID.toString());
    }

    public void setAmount(BigDecimal var) {
        set(Fields.AMOUNT.toString(), var);
    }

    public BigDecimal getAmount() {
        return (BigDecimal) get(Fields.AMOUNT.toString());
    }

    public void setNote(String var) {
        set(Fields.NOTE.toString(), var);
    }

    public String getNote() {
        return (String) get(Fields.NOTE.toString());
    }

    public void setCreatedDate(Date var) {
        set(Fields.CREATED_DATE.toString(), var);
    }

    public Date getCreatedDate() {
        return (Date) get(Fields.CREATED_DATE.toString());
    }

    public void setOrderNumber(String var) {
        set(Fields.ORDER_NUMBER.toString(), var);
    }

    public String getOrderNumber() {
        return (String) get(Fields.ORDER_NUMBER.toString());
    }

    public void setOrderId(Integer var) {
        set(Fields.ORDER_ID.toString(), var);
    }

    public Integer getOrderId() {
        return (Integer) get(Fields.ORDER_ID.toString());
    }

    public void setOrderItemId(Integer var) {
        set(Fields.ORDER_ITEM_ID.toString(), var);
    }

    public Integer getOrderItemId() {
        return (Integer) get(Fields.ORDER_ITEM_ID.toString());
    }

    public void setProductName(String var) {
        set(Fields.PRODUCT_NAME.toString(), var);
    }

    public String getProductName() {
        return (String) get(Fields.PRODUCT_NAME.toString());
    }

    public void setProductSettlementProportion(BigDecimal var) {
        set(Fields.PRODUCT_SETTLEMENT_PROPORTION.toString(), var);
    }

    public BigDecimal getProductSettlementProportion() {
        return (BigDecimal) get(Fields.PRODUCT_SETTLEMENT_PROPORTION.toString());
    }

    public void setExpectedReward(BigDecimal var) {
        set(Fields.EXPECTED_REWARD.toString(), var);
    }

    public BigDecimal getExpectedReward() {
        return (BigDecimal) get(Fields.EXPECTED_REWARD.toString());
    }

    public void setExpectedRewardLv1(BigDecimal var) {
        set(Fields.EXPECTED_REWARD_LV1.toString(), var);
    }

    public BigDecimal getExpectedRewardLv1() {
        return (BigDecimal) get(Fields.EXPECTED_REWARD_LV1.toString());
    }

    public void setExpectedRewardLv2(BigDecimal var) {
        set(Fields.EXPECTED_REWARD_LV2.toString(), var);
    }

    public BigDecimal getExpectedRewardLv2() {
        return (BigDecimal) get(Fields.EXPECTED_REWARD_LV2.toString());
    }

    public void setSettlementProportionLv1(BigDecimal var) {
        set(Fields.SETTLEMENT_PROPORTION_LV1.toString(), var);
    }

    public BigDecimal getSettlementProportionLv1() {
        return (BigDecimal) get(Fields.SETTLEMENT_PROPORTION_LV1.toString());
    }

    public void setSettlementProportionLv2(BigDecimal var) {
        set(Fields.SETTLEMENT_PROPORTION_LV2.toString(), var);
    }

    public BigDecimal getSettlementProportionLv2() {
        return (BigDecimal) get(Fields.SETTLEMENT_PROPORTION_LV2.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
