/*
 *   Copyright (C) 2014-2019 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.partner.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class PhysicalPurchaseSummaryBase<M extends PhysicalPurchaseSummaryBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        SELLER_ID("seller_id"),
        MONTHLY_AMOUNT("monthly_amount"),
        MONTHLY_SETTLED_AMOUNT("monthly_settled_amount"),
        MONTHLY_EXPECTED_SETTLED_AMOUNT("monthly_expected_settled_amount"),
        STATISTIC_MONTH("statistic_month"),
        SETTLEMENT_PROPORTION("settlement_proportion"),
        TRANSFERRED("transferred"),
        TRANSFERRED_AMOUNT("transferred_amount"),
        MONTHLY_EXPECTED_SETTLED_AMOUNT_LV2("monthly_expected_settled_amount_lv2");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setSellerId(Integer var) {
        set(Fields.SELLER_ID.toString(), var);
    }

    public Integer getSellerId() {
        return (Integer) get(Fields.SELLER_ID.toString());
    }

    public void setMonthlyAmount(BigDecimal var) {
        set(Fields.MONTHLY_AMOUNT.toString(), var);
    }

    public BigDecimal getMonthlyAmount() {
        return (BigDecimal) get(Fields.MONTHLY_AMOUNT.toString());
    }

    public void setMonthlySettledAmount(BigDecimal var) {
        set(Fields.MONTHLY_SETTLED_AMOUNT.toString(), var);
    }

    public BigDecimal getMonthlySettledAmount() {
        return (BigDecimal) get(Fields.MONTHLY_SETTLED_AMOUNT.toString());
    }

    public void setMonthlyExpectedSettledAmount(BigDecimal var) {
        set(Fields.MONTHLY_EXPECTED_SETTLED_AMOUNT.toString(), var);
    }

    public BigDecimal getMonthlyExpectedSettledAmount() {
        return (BigDecimal) get(Fields.MONTHLY_EXPECTED_SETTLED_AMOUNT.toString());
    }

    public void setStatisticMonth(Date var) {
        set(Fields.STATISTIC_MONTH.toString(), var);
    }

    public Date getStatisticMonth() {
        return (Date) get(Fields.STATISTIC_MONTH.toString());
    }

    public void setSettlementProportion(BigDecimal var) {
        set(Fields.SETTLEMENT_PROPORTION.toString(), var);
    }

    public BigDecimal getSettlementProportion() {
        return (BigDecimal) get(Fields.SETTLEMENT_PROPORTION.toString());
    }

    public void setTransferred(Integer var) {
        set(Fields.TRANSFERRED.toString(), var);
    }

    public Integer getTransferred() {
        return (Integer) get(Fields.TRANSFERRED.toString());
    }

    public void setTransferredAmount(BigDecimal var) {
        set(Fields.TRANSFERRED_AMOUNT.toString(), var);
    }

    public BigDecimal getTransferredAmount() {
        return (BigDecimal) get(Fields.TRANSFERRED_AMOUNT.toString());
    }

    public void setMonthlyExpectedSettledAmountLv2(BigDecimal var) {
        set(Fields.MONTHLY_EXPECTED_SETTLED_AMOUNT_LV2.toString(), var);
    }

    public BigDecimal getMonthlyExpectedSettledAmountLv2() {
        return (BigDecimal) get(Fields.MONTHLY_EXPECTED_SETTLED_AMOUNT_LV2.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
