/*
 *   Copyright (C) 2014-2019 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.partner.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class SellerBase<M extends SellerBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        USER_ID("user_id"),
        PARENT_ID("parent_id"),
        PARTNER_SHIP("partner_ship"),
        PARTNER_ID("partner_id"),
        SELLER_SHIP("seller_ship"),
        LEVEL("level"),
        PARTNER_SHIP_TIME("partner_ship_time"),
        SELLER_SHIP_TIME("seller_ship_time"),
        PARTNER_LEVEL_ID("partner_level_id"),
        CROWN_SHIP("crown_ship"),
        CROWN_SHIP_TEMP("crown_ship_temp"),
        CROWN_SHIP_TIME("crown_ship_time"),
        CROWN_ID("crown_id"),
        CROWN_APPLY_FAILURE_TIMES("crown_apply_failure_times");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setUserId(Integer var) {
        set(Fields.USER_ID.toString(), var);
    }

    public Integer getUserId() {
        return (Integer) get(Fields.USER_ID.toString());
    }

    public void setParentId(Integer var) {
        set(Fields.PARENT_ID.toString(), var);
    }

    public Integer getParentId() {
        return (Integer) get(Fields.PARENT_ID.toString());
    }

    public void setPartnerShip(Integer var) {
        set(Fields.PARTNER_SHIP.toString(), var);
    }

    public Integer getPartnerShip() {
        return (Integer) get(Fields.PARTNER_SHIP.toString());
    }

    public void setPartnerId(Integer var) {
        set(Fields.PARTNER_ID.toString(), var);
    }

    public Integer getPartnerId() {
        return (Integer) get(Fields.PARTNER_ID.toString());
    }

    public void setSellerShip(Integer var) {
        set(Fields.SELLER_SHIP.toString(), var);
    }

    public Integer getSellerShip() {
        return (Integer) get(Fields.SELLER_SHIP.toString());
    }

    public void setLevel(Integer var) {
        set(Fields.LEVEL.toString(), var);
    }

    public Integer getLevel() {
        return (Integer) get(Fields.LEVEL.toString());
    }

    public void setPartnerShipTime(Date var) {
        set(Fields.PARTNER_SHIP_TIME.toString(), var);
    }

    public Date getPartnerShipTime() {
        return (Date) get(Fields.PARTNER_SHIP_TIME.toString());
    }

    public void setSellerShipTime(Date var) {
        set(Fields.SELLER_SHIP_TIME.toString(), var);
    }

    public Date getSellerShipTime() {
        return (Date) get(Fields.SELLER_SHIP_TIME.toString());
    }

    public void setPartnerLevelId(Integer var) {
        set(Fields.PARTNER_LEVEL_ID.toString(), var);
    }

    public Integer getPartnerLevelId() {
        return (Integer) get(Fields.PARTNER_LEVEL_ID.toString());
    }

    public void setCrownShip(Integer var) {
        set(Fields.CROWN_SHIP.toString(), var);
    }

    public Integer getCrownShip() {
        return (Integer) get(Fields.CROWN_SHIP.toString());
    }

    public void setCrownShipTemp(Integer var) {
        set(Fields.CROWN_SHIP_TEMP.toString(), var);
    }

    public Integer getCrownShipTemp() {
        return (Integer) get(Fields.CROWN_SHIP_TEMP.toString());
    }

    public void setCrownShipTime(Date var) {
        set(Fields.CROWN_SHIP_TIME.toString(), var);
    }

    public Date getCrownShipTime() {
        return (Date) get(Fields.CROWN_SHIP_TIME.toString());
    }

    public void setCrownId(Integer var) {
        set(Fields.CROWN_ID.toString(), var);
    }

    public Integer getCrownId() {
        return (Integer) get(Fields.CROWN_ID.toString());
    }

    public void setCrownApplyFailureTimes(Integer var) {
        set(Fields.CROWN_APPLY_FAILURE_TIMES.toString(), var);
    }

    public Integer getCrownApplyFailureTimes() {
        return (Integer) get(Fields.CROWN_APPLY_FAILURE_TIMES.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
