version: "3"
services:
  webapp:
    image: biliya:webapp
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.buildkit
    command:
      - /bin/sh
      - -c
      - |
        cp /usr/src/mall-webapp/target/*.war /var/webapps
