version: "3"
services:
  war:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.buildwar
    volumes:
      - ./target:/var/webapps      
    command:
      - /bin/sh
      - -c
      - |
        cp /usr/src/mall-webapp/target/*.war /var/webapps
