/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.marketing.piece.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class PieceGroupPurchaseBase<M extends PieceGroupPurchaseBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        MARKETING_NAME("marketing_name"),
        MARKETING_SHORT_NAME("marketing_short_name"),
        MIN_PARTICIPATOR_COUNT("min_participator_count"),
        DURATION("duration"),
        PRICE("price"),
        SUGGESTED_PRICE("suggested_price"),
        SALE("sale"),
        DESCRIPTION("description"),
        COVER("cover"),
        PRODUCT_ID("product_id"),
        STATUS("status"),
        MASTER_FREE("master_free"),
        FREE_SHIPPING("free_shipping"),
        COUPON_USAGE("coupon_usage"),
        PAYMENT_TYPE("payment_type"),
        COUPON_STRATEGY_SERVICE_NAME("coupon_strategy_service_name"),
        SORT_ORDER("sort_order");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setMarketingName(String var) {
        set(Fields.MARKETING_NAME.toString(), var);
    }

    public String getMarketingName() {
        return (String) get(Fields.MARKETING_NAME.toString());
    }

    public void setMarketingShortName(String var) {
        set(Fields.MARKETING_SHORT_NAME.toString(), var);
    }

    public String getMarketingShortName() {
        return (String) get(Fields.MARKETING_SHORT_NAME.toString());
    }

    public void setMinParticipatorCount(Integer var) {
        set(Fields.MIN_PARTICIPATOR_COUNT.toString(), var);
    }

    public Integer getMinParticipatorCount() {
        return (Integer) get(Fields.MIN_PARTICIPATOR_COUNT.toString());
    }

    public void setDuration(Integer var) {
        set(Fields.DURATION.toString(), var);
    }

    public Integer getDuration() {
        return (Integer) get(Fields.DURATION.toString());
    }

    public void setPrice(BigDecimal var) {
        set(Fields.PRICE.toString(), var);
    }

    public BigDecimal getPrice() {
        return (BigDecimal) get(Fields.PRICE.toString());
    }

    public void setSuggestedPrice(BigDecimal var) {
        set(Fields.SUGGESTED_PRICE.toString(), var);
    }

    public BigDecimal getSuggestedPrice() {
        return (BigDecimal) get(Fields.SUGGESTED_PRICE.toString());
    }

    public void setSale(Integer var) {
        set(Fields.SALE.toString(), var);
    }

    public Integer getSale() {
        return (Integer) get(Fields.SALE.toString());
    }

    public void setDescription(String var) {
        set(Fields.DESCRIPTION.toString(), var);
    }

    public String getDescription() {
        return (String) get(Fields.DESCRIPTION.toString());
    }

    public void setCover(String var) {
        set(Fields.COVER.toString(), var);
    }

    public String getCover() {
        return (String) get(Fields.COVER.toString());
    }

    public void setProductId(Integer var) {
        set(Fields.PRODUCT_ID.toString(), var);
    }

    public Integer getProductId() {
        return (Integer) get(Fields.PRODUCT_ID.toString());
    }

    public void setStatus(String var) {
        set(Fields.STATUS.toString(), var);
    }

    public String getStatus() {
        return (String) get(Fields.STATUS.toString());
    }

    public void setMasterFree(Integer var) {
        set(Fields.MASTER_FREE.toString(), var);
    }

    public Integer getMasterFree() {
        return (Integer) get(Fields.MASTER_FREE.toString());
    }

    public void setFreeShipping(Integer var) {
        set(Fields.FREE_SHIPPING.toString(), var);
    }

    public Integer getFreeShipping() {
        return (Integer) get(Fields.FREE_SHIPPING.toString());
    }

    public void setCouponUsage(Integer var) {
        set(Fields.COUPON_USAGE.toString(), var);
    }

    public Integer getCouponUsage() {
        return (Integer) get(Fields.COUPON_USAGE.toString());
    }

    public void setPaymentType(String var) {
        set(Fields.PAYMENT_TYPE.toString(), var);
    }

    public String getPaymentType() {
        return (String) get(Fields.PAYMENT_TYPE.toString());
    }

    public void setCouponStrategyServiceName(String var) {
        set(Fields.COUPON_STRATEGY_SERVICE_NAME.toString(), var);
    }

    public String getCouponStrategyServiceName() {
        return (String) get(Fields.COUPON_STRATEGY_SERVICE_NAME.toString());
    }

    public void setSortOrder(Integer var) {
        set(Fields.SORT_ORDER.toString(), var);
    }

    public Integer getSortOrder() {
        return (Integer) get(Fields.SORT_ORDER.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
