/*
 *   Copyright (C) 2014-2018 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.marketing.piece.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class PieceGroupPurchaseMasterBase<M extends PieceGroupPurchaseMasterBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        PIECE_GROUP_PURCHASE_ID("piece_group_purchase_id"),
        USER_ID("user_id"),
        START_TIME("start_time"),
        END_TIME("end_time"),
        STATUS("status"),
        PROMOTED("promoted");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setPieceGroupPurchaseId(Integer var) {
        set(Fields.PIECE_GROUP_PURCHASE_ID.toString(), var);
    }

    public Integer getPieceGroupPurchaseId() {
        return (Integer) get(Fields.PIECE_GROUP_PURCHASE_ID.toString());
    }

    public void setUserId(Integer var) {
        set(Fields.USER_ID.toString(), var);
    }

    public Integer getUserId() {
        return (Integer) get(Fields.USER_ID.toString());
    }

    public void setStartTime(Date var) {
        set(Fields.START_TIME.toString(), var);
    }

    public Date getStartTime() {
        return (Date) get(Fields.START_TIME.toString());
    }

    public void setEndTime(Date var) {
        set(Fields.END_TIME.toString(), var);
    }

    public Date getEndTime() {
        return (Date) get(Fields.END_TIME.toString());
    }

    public void setStatus(String var) {
        set(Fields.STATUS.toString(), var);
    }

    public String getStatus() {
        return (String) get(Fields.STATUS.toString());
    }

    public void setPromoted(Integer var) {
        set(Fields.PROMOTED.toString(), var);
    }

    public Integer getPromoted() {
        return (Integer) get(Fields.PROMOTED.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
