/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.identity.model;

import com.jfeat.identity.model.base.PermissionDefinitionBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

@TableBind(tableName = "t_permission_definition")
public class PermissionDefinition extends PermissionDefinitionBase<PermissionDefinition> {

    /**
     * Only use for query.
     */
    public static PermissionDefinition dao = new PermissionDefinition();

    public List<PermissionDefinition> findByGroupIdentifier(String groupIdentifier) {
        return findByField(Fields.GROUP_IDENTIFIER.toString(), groupIdentifier);
    }

    public boolean updateGroupIdentifier(String groupIdentifier) {
        return Db.update("update t_permission_definition set group_identifier = ? where identifier = ?", groupIdentifier, getIdentifier()) > 0;
    }
}
