/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.identity.model;

import com.jfeat.identity.model.base.PermissionGroupDefinitionBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.Arrays;
import java.util.List;

@TableBind(tableName = "t_permission_group_definition")
public class PermissionGroupDefinition extends PermissionGroupDefinitionBase<PermissionGroupDefinition> {

    public static final Integer VISIBLE = 1;
    public static final Integer INVISIBLE = 0;

    /**
     * Only use for query.
     */
    public static PermissionGroupDefinition dao = new PermissionGroupDefinition();

    @Deprecated
    public List<String> getPermissionList() {
        return Arrays.asList(getPermissions().split("\\|"));
    }

    public List<PermissionDefinition> getPermissionDefinitions() {
        return PermissionDefinition.dao.findByGroupIdentifier(getIdentifier());
    }

    public List<PermissionGroupDefinition> findVisible() {
        return findByField(Fields.VISIBLE.toString(), VISIBLE);
    }
}
