/*
 *   Copyright (C) 2014-2019 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.identity.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class UserBase<M extends UserBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        LOGIN_NAME("login_name"),
        NAME("name"),
        REAL_NAME("real_name"),
        PASSWORD("password"),
        EMAIL("email"),
        PHONE("phone"),
        WEIXIN("weixin"),
        REGISTER_DATE("register_date"),
        LAST_LOGIN_DATE("last_login_date"),
        SALT("salt"),
        STATUS("status"),
        TOKEN_SALT("token_salt"),
        TOKEN_EXPIRED_DATE("token_expired_date"),
        INVITATION_CODE("invitation_code"),
        INVITER_ID("inviter_id"),
        AVATAR("avatar"),
        SEX("sex"),
        BIRTHDAY("birthday"),
        DETAILS("details"),
        UID("uid"),
        FOLLOWED("followed"),
        FOLLOW_TIME("follow_time"),
        INVITATION_QRCODE_URL("invitation_qrcode_url"),
        INVITATION_QRCODE("invitation_qrcode"),
        WX_UNIONID("wx_unionid"),
        WXA_OPENID("wxa_openid"),
        WXAPP_OPENID("wxapp_openid"),
        APP_USER("app_user"),
        WECHAT_NAME("wechat_name"),
        GRADE("grade"),
        CONTACT_PHONE("contact_phone"),
        CONTACT_WX_NUMBER("contact_wx_number"),
        CABIN_CODE("cabin_code"),
        STORE_CODE("store_code"),
        ASSISTANT_CODE("assistant_code");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" IS NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setLoginName(String var) {
        set(Fields.LOGIN_NAME.toString(), var);
    }

    public String getLoginName() {
        return (String) get(Fields.LOGIN_NAME.toString());
    }

    public void setName(String var) {
        set(Fields.NAME.toString(), var);
    }

    public String getName() {
        return (String) get(Fields.NAME.toString());
    }

    public void setRealName(String var) {
        set(Fields.REAL_NAME.toString(), var);
    }

    public String getRealName() {
        return (String) get(Fields.REAL_NAME.toString());
    }

    public void setPassword(String var) {
        set(Fields.PASSWORD.toString(), var);
    }

    public String getPassword() {
        return (String) get(Fields.PASSWORD.toString());
    }

    public void setEmail(String var) {
        set(Fields.EMAIL.toString(), var);
    }

    public String getEmail() {
        return (String) get(Fields.EMAIL.toString());
    }

    public void setPhone(String var) {
        set(Fields.PHONE.toString(), var);
    }

    public String getPhone() {
        return (String) get(Fields.PHONE.toString());
    }

    public void setWeixin(String var) {
        set(Fields.WEIXIN.toString(), var);
    }

    public String getWeixin() {
        return (String) get(Fields.WEIXIN.toString());
    }

    public void setRegisterDate(Date var) {
        set(Fields.REGISTER_DATE.toString(), var);
    }

    public Date getRegisterDate() {
        return (Date) get(Fields.REGISTER_DATE.toString());
    }

    public void setLastLoginDate(Date var) {
        set(Fields.LAST_LOGIN_DATE.toString(), var);
    }

    public Date getLastLoginDate() {
        return (Date) get(Fields.LAST_LOGIN_DATE.toString());
    }

    public void setSalt(String var) {
        set(Fields.SALT.toString(), var);
    }

    public String getSalt() {
        return (String) get(Fields.SALT.toString());
    }

    public void setStatus(String var) {
        set(Fields.STATUS.toString(), var);
    }

    public String getStatus() {
        return (String) get(Fields.STATUS.toString());
    }

    public void setTokenSalt(String var) {
        set(Fields.TOKEN_SALT.toString(), var);
    }

    public String getTokenSalt() {
        return (String) get(Fields.TOKEN_SALT.toString());
    }

    public void setTokenExpiredDate(Date var) {
        set(Fields.TOKEN_EXPIRED_DATE.toString(), var);
    }

    public Date getTokenExpiredDate() {
        return (Date) get(Fields.TOKEN_EXPIRED_DATE.toString());
    }

    public void setInvitationCode(String var) {
        set(Fields.INVITATION_CODE.toString(), var);
    }

    public String getInvitationCode() {
        return (String) get(Fields.INVITATION_CODE.toString());
    }

    public void setInviterId(Integer var) {
        set(Fields.INVITER_ID.toString(), var);
    }

    public Integer getInviterId() {
        return (Integer) get(Fields.INVITER_ID.toString());
    }

    public void setAvatar(String var) {
        set(Fields.AVATAR.toString(), var);
    }

    public String getAvatar() {
        return (String) get(Fields.AVATAR.toString());
    }

    public void setSex(Integer var) {
        set(Fields.SEX.toString(), var);
    }

    public Integer getSex() {
        return (Integer) get(Fields.SEX.toString());
    }

    public void setBirthday(Date var) {
        set(Fields.BIRTHDAY.toString(), var);
    }

    public Date getBirthday() {
        return (Date) get(Fields.BIRTHDAY.toString());
    }

    public void setDetails(String var) {
        set(Fields.DETAILS.toString(), var);
    }

    public String getDetails() {
        return (String) get(Fields.DETAILS.toString());
    }

    public void setUid(String var) {
        set(Fields.UID.toString(), var);
    }

    public String getUid() {
        return (String) get(Fields.UID.toString());
    }

    public void setFollowed(Integer var) {
        set(Fields.FOLLOWED.toString(), var);
    }

    public Integer getFollowed() {
        return (Integer) get(Fields.FOLLOWED.toString());
    }

    public void setFollowTime(Date var) {
        set(Fields.FOLLOW_TIME.toString(), var);
    }

    public Date getFollowTime() {
        return (Date) get(Fields.FOLLOW_TIME.toString());
    }

    public void setInvitationQrcodeUrl(String var) {
        set(Fields.INVITATION_QRCODE_URL.toString(), var);
    }

    public String getInvitationQrcodeUrl() {
        return (String) get(Fields.INVITATION_QRCODE_URL.toString());
    }

    public void setInvitationQrcode(String var) {
        set(Fields.INVITATION_QRCODE.toString(), var);
    }

    public String getInvitationQrcode() {
        return (String) get(Fields.INVITATION_QRCODE.toString());
    }

    public void setWxUnionid(String var) {
        set(Fields.WX_UNIONID.toString(), var);
    }

    public String getWxUnionid() {
        return (String) get(Fields.WX_UNIONID.toString());
    }

    public void setWxaOpenid(String var) {
        set(Fields.WXA_OPENID.toString(), var);
    }

    public String getWxaOpenid() {
        return (String) get(Fields.WXA_OPENID.toString());
    }

    public void setWxappOpenid(String var) {
        set(Fields.WXAPP_OPENID.toString(), var);
    }

    public String getWxappOpenid() {
        return (String) get(Fields.WXAPP_OPENID.toString());
    }

    public void setAppUser(Integer var) {
        set(Fields.APP_USER.toString(), var);
    }

    public Integer getAppUser() {
        return (Integer) get(Fields.APP_USER.toString());
    }

    public void setWechatName(String var) {
        set(Fields.WECHAT_NAME.toString(), var);
    }

    public String getWechatName() {
        return (String) get(Fields.WECHAT_NAME.toString());
    }

    public void setGrade(String var) {
        set(Fields.GRADE.toString(), var);
    }

    public String getGrade() {
        return (String) get(Fields.GRADE.toString());
    }

    public void setContactPhone(String var) {
        set(Fields.CONTACT_PHONE.toString(), var);
    }

    public String getContactPhone() {
        return (String) get(Fields.CONTACT_PHONE.toString());
    }

    public void setContactWxNumber(String var) {
        set(Fields.CONTACT_WX_NUMBER.toString(), var);
    }

    public String getContactWxNumber() {
        return (String) get(Fields.CONTACT_WX_NUMBER.toString());
    }

    public void setCabinCode(String var) {
        set(Fields.CABIN_CODE.toString(), var);
    }

    public String getCabinCode() {
        return (String) get(Fields.CABIN_CODE.toString());
    }

    public void setStoreCode(String var) {
        set(Fields.STORE_CODE.toString(), var);
    }

    public String getStoreCode() {
        return (String) get(Fields.STORE_CODE.toString());
    }

    public void setAssistantCode(String var) {
        set(Fields.ASSISTANT_CODE.toString(), var);
    }

    public String getAssistantCode() {
        return (String) get(Fields.ASSISTANT_CODE.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
