/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.settlement.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class OrderItemRewardBase<M extends OrderItemRewardBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        ORDER_ID("order_id"),
        ORDER_NUMBER("order_number"),
        ORDER_TOTAL_PRICE("order_total_price"),
        ORDER_CREATED_TIME("order_created_time"),
        ORDER_PAID_TIME("order_paid_time"),
        ORDER_ITEM_ID("order_item_id"),
        ORDER_PROFIT("order_profit"),
        PERCENT("percent"),
        REWARD("reward"),
        OWNER_ID("owner_id"),
        LEVEL("level"),
        STATE("state"),
        TYPE("type"),
        CREATED_TIME("created_time"),
        SETTLED_TIME("settled_time"),
        WITHDRAWN_TIME("withdrawn_time"),
        ORDER_USER_NAME("order_user_name"),
        PAYMENT_TYPE("payment_type"),
        POINT_EXCHANGE_RATE("point_exchange_rate");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setOrderId(Integer var) {
        set(Fields.ORDER_ID.toString(), var);
    }

    public Integer getOrderId() {
        return (Integer) get(Fields.ORDER_ID.toString());
    }

    public void setOrderNumber(String var) {
        set(Fields.ORDER_NUMBER.toString(), var);
    }

    public String getOrderNumber() {
        return (String) get(Fields.ORDER_NUMBER.toString());
    }

    public void setOrderTotalPrice(BigDecimal var) {
        set(Fields.ORDER_TOTAL_PRICE.toString(), var);
    }

    public BigDecimal getOrderTotalPrice() {
        return (BigDecimal) get(Fields.ORDER_TOTAL_PRICE.toString());
    }

    public void setOrderCreatedTime(Date var) {
        set(Fields.ORDER_CREATED_TIME.toString(), var);
    }

    public Date getOrderCreatedTime() {
        return (Date) get(Fields.ORDER_CREATED_TIME.toString());
    }

    public void setOrderPaidTime(Date var) {
        set(Fields.ORDER_PAID_TIME.toString(), var);
    }

    public Date getOrderPaidTime() {
        return (Date) get(Fields.ORDER_PAID_TIME.toString());
    }

    public void setOrderItemId(Integer var) {
        set(Fields.ORDER_ITEM_ID.toString(), var);
    }

    public Integer getOrderItemId() {
        return (Integer) get(Fields.ORDER_ITEM_ID.toString());
    }

    public void setOrderProfit(BigDecimal var) {
        set(Fields.ORDER_PROFIT.toString(), var);
    }

    public BigDecimal getOrderProfit() {
        return (BigDecimal) get(Fields.ORDER_PROFIT.toString());
    }

    public void setPercent(Integer var) {
        set(Fields.PERCENT.toString(), var);
    }

    public Integer getPercent() {
        return (Integer) get(Fields.PERCENT.toString());
    }

    public void setReward(BigDecimal var) {
        set(Fields.REWARD.toString(), var);
    }

    public BigDecimal getReward() {
        return (BigDecimal) get(Fields.REWARD.toString());
    }

    public void setOwnerId(Integer var) {
        set(Fields.OWNER_ID.toString(), var);
    }

    public Integer getOwnerId() {
        return (Integer) get(Fields.OWNER_ID.toString());
    }

    public void setLevel(Integer var) {
        set(Fields.LEVEL.toString(), var);
    }

    public Integer getLevel() {
        return (Integer) get(Fields.LEVEL.toString());
    }

    public void setState(String var) {
        set(Fields.STATE.toString(), var);
    }

    public String getState() {
        return (String) get(Fields.STATE.toString());
    }

    public void setType(String var) {
        set(Fields.TYPE.toString(), var);
    }

    public String getType() {
        return (String) get(Fields.TYPE.toString());
    }

    public void setCreatedTime(Date var) {
        set(Fields.CREATED_TIME.toString(), var);
    }

    public Date getCreatedTime() {
        return (Date) get(Fields.CREATED_TIME.toString());
    }

    public void setSettledTime(Date var) {
        set(Fields.SETTLED_TIME.toString(), var);
    }

    public Date getSettledTime() {
        return (Date) get(Fields.SETTLED_TIME.toString());
    }

    public void setWithdrawnTime(Date var) {
        set(Fields.WITHDRAWN_TIME.toString(), var);
    }

    public Date getWithdrawnTime() {
        return (Date) get(Fields.WITHDRAWN_TIME.toString());
    }

    public void setOrderUserName(String var) {
        set(Fields.ORDER_USER_NAME.toString(), var);
    }

    public String getOrderUserName() {
        return (String) get(Fields.ORDER_USER_NAME.toString());
    }

    public void setPaymentType(String var) {
        set(Fields.PAYMENT_TYPE.toString(), var);
    }

    public String getPaymentType() {
        return (String) get(Fields.PAYMENT_TYPE.toString());
    }

    public void setPointExchangeRate(Integer var) {
        set(Fields.POINT_EXCHANGE_RATE.toString(), var);
    }

    public Integer getPointExchangeRate() {
        return (Integer) get(Fields.POINT_EXCHANGE_RATE.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
