/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.settlement.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class RewardCashBase<M extends RewardCashBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        OWNER_ID("owner_id"),
        CASH("cash"),
        APPLY_TIME("apply_time"),
        REJECT_TIME("reject_time"),
        COMPLETE_TIME("complete_time"),
        STATUS("status"),
        ACCOUNT_TYPE("account_type"),
        ACCOUNT_NUMBER("account_number"),
        ACCOUNT_NAME("account_name"),
        BANK_NAME("bank_name"),
        NOTE("note");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String gt(Object obj) {
            return new StringBuilder(this.toString()).append(">").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setOwnerId(Integer var) {
        set(Fields.OWNER_ID.toString(), var);
    }

    public Integer getOwnerId() {
        return (Integer) get(Fields.OWNER_ID.toString());
    }

    public void setCash(BigDecimal var) {
        set(Fields.CASH.toString(), var);
    }

    public BigDecimal getCash() {
        return (BigDecimal) get(Fields.CASH.toString());
    }

    public void setApplyTime(Date var) {
        set(Fields.APPLY_TIME.toString(), var);
    }

    public Date getApplyTime() {
        return (Date) get(Fields.APPLY_TIME.toString());
    }

    public void setRejectTime(Date var) {
        set(Fields.REJECT_TIME.toString(), var);
    }

    public Date getRejectTime() {
        return (Date) get(Fields.REJECT_TIME.toString());
    }

    public void setCompleteTime(Date var) {
        set(Fields.COMPLETE_TIME.toString(), var);
    }

    public Date getCompleteTime() {
        return (Date) get(Fields.COMPLETE_TIME.toString());
    }

    public void setStatus(String var) {
        set(Fields.STATUS.toString(), var);
    }

    public String getStatus() {
        return (String) get(Fields.STATUS.toString());
    }

    public void setAccountType(String var) {
        set(Fields.ACCOUNT_TYPE.toString(), var);
    }

    public String getAccountType() {
        return (String) get(Fields.ACCOUNT_TYPE.toString());
    }

    public void setAccountNumber(String var) {
        set(Fields.ACCOUNT_NUMBER.toString(), var);
    }

    public String getAccountNumber() {
        return (String) get(Fields.ACCOUNT_NUMBER.toString());
    }

    public void setAccountName(String var) {
        set(Fields.ACCOUNT_NAME.toString(), var);
    }

    public String getAccountName() {
        return (String) get(Fields.ACCOUNT_NAME.toString());
    }

    public void setBankName(String var) {
        set(Fields.BANK_NAME.toString(), var);
    }

    public String getBankName() {
        return (String) get(Fields.BANK_NAME.toString());
    }

    public void setNote(String var) {
        set(Fields.NOTE.toString(), var);
    }

    public String getNote() {
        return (String) get(Fields.NOTE.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
