/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.order.model;

import com.jfeat.kit.SqlUpdate;
import com.jfeat.order.model.base.ExpressBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

@TableBind(tableName = "t_express")
public class Express extends ExpressBase<Express> {

    public static final int DEFAULT_EXPRESS = 1;

    /**
     * Only use for query.
     */
    public static Express dao = new Express();

    public List<Express> findAllEnabled() {
        return find("select * from t_express where enabled=1 order by is_default desc");
    }

    public Express findByCode(String code) {
        return findFirst("select * from t_express where code=?", code);
    }

    public Express findDefaultExpress() {
        return findFirst("select * from t_express where is_default=1");
    }

    public boolean save() {
        if (getIsDefault() != null && getIsDefault() == DEFAULT_EXPRESS) {
            clearDefault();
        }
        remove(Fields.ID.toString());
        return super.save();
    }

    public boolean update() {
        if (getIsDefault() != null && getIsDefault() == DEFAULT_EXPRESS) {
            clearDefault();
        }
        return super.update();
    }

    private void clearDefault() {
        SqlUpdate clear = new SqlUpdate();
        clear.update(getTableName());
        clear.set(Fields.IS_DEFAULT.toString(), 0);
        Db.update(clear.sql());
    }
}
