/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.order.model;

import com.jfeat.order.model.base.OrderStatisticBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.Date;
import java.util.List;

@TableBind(tableName = "t_order_statistic")
public class OrderStatistic extends OrderStatisticBase<OrderStatistic> {

    /**
     * Only use for query.
     */
    public static OrderStatistic dao = new OrderStatistic();

    public boolean save() {
        setCreatedDate(new Date());
        return super.save();
    }

    public List<OrderStatistic> queryStatistic(String fromDate, String toDate) {
        return find("select * from t_order_statistic where created_date>=? and created_date<=?", fromDate, toDate);
    }
}
