/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.misc.model;

import com.jfeat.misc.model.base.AboutMallBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

@TableBind(tableName = "t_about_mall")
public class AboutMall extends AboutMallBase<AboutMall> {

    /**
     * Only use for query.
     */
    public static AboutMall dao = new AboutMall();

    public AboutMall getDefault() {
        AboutMall aboutMall = findFirst("select * from t_about_mall");
        if (aboutMall == null) {
            aboutMall = new AboutMall();
            aboutMall.save();
            //retrieve to get full attributes
            aboutMall = findFirst("select * from t_about_mall");
        }
        return aboutMall;
    }
}
