/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.misc.model;

import com.jfeat.misc.model.base.AdLinkDefinitionBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_ad_link_definition")
public class AdLinkDefinition extends AdLinkDefinitionBase<AdLinkDefinition> {

    public static final int FUNCTIONAL_LINK = 0;
    public static final int PRODUCT_LINK = 1;
    public static final int CATEGORY_LINK = 2;

    /**
     * Only use for query.
     */
    public static AdLinkDefinition dao = new AdLinkDefinition();

    public List<AdLinkDefinition> findFunctionalLink() {
        return find("select * from t_ad_link_definition where type=?", FUNCTIONAL_LINK);
    }

    public AdLinkDefinition findProductLink() {
        return findFirst("select * from t_ad_link_definition where type=?", PRODUCT_LINK);
    }

    public AdLinkDefinition findCategoryLink() {
        return findFirst("select * from t_ad_link_definition where type=?", CATEGORY_LINK);
    }
}
