/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.misc.model;

import com.jfeat.misc.model.base.FaqBase;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

import java.util.ArrayList;
import java.util.Date;

@TableBind(tableName = "t_faq")
public class Faq extends FaqBase<Faq> {

    /**
     * Only use for query.
     */
    public static Faq dao = new Faq();

    public Page<Record> paginate(int pageNumber, int pageSize, Integer typeId) {
        ArrayList params = new ArrayList();
        StringBuilder select = new StringBuilder("select f.*, t.name as type_name");
        StringBuilder query = new StringBuilder();
        query.append("from t_faq f join t_faq_type t on f.type_id=t.id ");
        String cond = " where ";
        if(typeId != null) {
            query.append(cond);
            query.append(Fields.TYPE_ID.eq("?"));
            params.add(typeId);
        }

        return Db.paginate(pageNumber, pageSize, select.toString(), query.toString(), params.toArray());
    }

    public boolean save() {
        setCreatedDate(new Date());
        setLastModifiedDate(new Date());
        return super.save();
    }

    public boolean update() {
        setLastModifiedDate(new Date());
        return super.update();
    }
}
