/*
 *   Copyright (C) 2014-2016 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines the model for the table. All customize operation should 
 * be written here. Such as query/update/delete.
 * The controller calls this object.
 */
package com.jfeat.misc.model;

import com.jfeat.misc.model.base.FeedbackImageBase;
import com.jfinal.ext.plugin.tablebind.TableBind;

import java.util.List;

@TableBind(tableName = "t_feedback_image")
public class FeedbackImage extends FeedbackImageBase<FeedbackImage> {

    /**
     * Only use for query.
     */
    public static FeedbackImage dao = new FeedbackImage();

    List<FeedbackImage> findByFeedbackId(int feedbackId) {
        return find("select * from t_feedback_image where feedback_id=?", feedbackId);
    }
}
