/*
 *   Copyright (C) 2014-2017 www.kequandian.net
 *
 *    The program may be used and/or copied only with the written permission
 *    from www.kequandian.net or in accordance with the terms and
 *    conditions stipulated in the agreement/contract under which the program
 *    has been supplied.
 *
 *    All rights reserved.
 *
 */

/*
 * This file is automatically generated by tools.
 * It defines fields related to the database table.
 *
 * DON'T EDIT IT. OTHERWIDE IT WILL BE OVERRIDE WHEN RE-GENERATING IF TABLE CHANGE.
 */
package com.jfeat.misc.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfeat.core.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

public abstract class FaqBase<M extends FaqBase<?>> extends BaseModel<M> implements IBean {

    /**
     * Table fields 
     */
    public enum Fields {
        ID("id"),
        TYPE_ID("type_id"),
        TITLE("title"),
        CONTENT("content"),
        CREATED_DATE("created_date"),
        LAST_MODIFIED_DATE("last_modified_date");
        
        private String name;
        Fields(String name) {
            this.name = name;
        }

        public String toString() {
            return name;
        }
        public String like(Object obj) {
            return new StringBuilder(this.toString()).append(" LIKE ").append(obj).toString();
        }
        public String eq(Object obj) {
            return new StringBuilder(this.toString()).append("=").append(obj).toString();
        }
        public String ge(Object obj) {
            return new StringBuilder(this.toString()).append(">=").append(obj).toString();
        }
        public String lt(Object obj) {
            return new StringBuilder(this.toString()).append("<").append(obj).toString();
        }
        public String le(Object obj) {
            return new StringBuilder(this.toString()).append("<=").append(obj).toString();
        }
        public String isNull() {
            return new StringBuilder(this.toString()).append(" IS NULL").toString();
        }
        public String notNull() {
            return new StringBuilder(this.toString()).append(" NOT NULL").toString();
        }
        public String notEquals(Object obj) {
            return new StringBuilder(this.toString()).append("<>").append(obj).toString();
        }
    }

    public void setId(Integer var) {
        set(Fields.ID.toString(), var);
    }

    public Integer getId() {
        return (Integer) get(Fields.ID.toString());
    }

    public void setTypeId(Integer var) {
        set(Fields.TYPE_ID.toString(), var);
    }

    public Integer getTypeId() {
        return (Integer) get(Fields.TYPE_ID.toString());
    }

    public void setTitle(String var) {
        set(Fields.TITLE.toString(), var);
    }

    public String getTitle() {
        return (String) get(Fields.TITLE.toString());
    }

    public void setContent(String var) {
        set(Fields.CONTENT.toString(), var);
    }

    public String getContent() {
        return (String) get(Fields.CONTENT.toString());
    }

    public void setCreatedDate(Date var) {
        set(Fields.CREATED_DATE.toString(), var);
    }

    public Date getCreatedDate() {
        return (Date) get(Fields.CREATED_DATE.toString());
    }

    public void setLastModifiedDate(Date var) {
        set(Fields.LAST_MODIFIED_DATE.toString(), var);
    }

    public Date getLastModifiedDate() {
        return (Date) get(Fields.LAST_MODIFIED_DATE.toString());
    }


    ///////////////////////////////////////////////////////////////////////////
    
}
